# Generated by Django 2.1.3 on 2018-12-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shasha', '0004_newarrivals'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signup', models.CharField(max_length=256)),
                ('usr', models.CharField(max_length=100)),
                ('psd', models.CharField(max_length=256)),
                ('rank', models.IntegerField(default=1)),
                ('token', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'shasha_register',
            },
        ),
    ]
